---
abstract: 'find common mistakes in RDFa files'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - Checker
  - HTML
  - Linter
  - RDF
  - RDFa
  - SemWeb
  - 'Semantic Web'
  - Validator
  - XHTML
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::RDFa::Linter
name: RDF-RDFa-Linter
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  RDF::Query: 0
  RDF::RDFa::Generator: 0
  RDF::RDFa::Parser: 0
  RDF::Trine: 0
  RDF::TrineX::Functions: 0
  XML::LibXML: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-RDFa-Linter
  homepage: https://metacpan.org/release/RDF-RDFa-Linter
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/RDF-RDFa-Linter/
version: 0.053
